spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8
    username: myid
    password: test

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      generate-ddl: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
