spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8
    username: myid
    password: test

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      generate-ddl: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
